### PR TITLE
Support reorder between sections

### PR DESCRIPTION
**Pull request by xslim**
Adds support for showing sections and reordering rows between sections

### CODE REVIEW

**Comment by hpique** [comment]
Thanks for this @xslim. I'll play with it as soon as I can.

**Comment by hpique** [comment]
Demo crashes on startup. Would you mind testing this a bit more?

**Comment by hpique** [comment]
Fixed the crash in this branch (feel free to cherry-pick). It'd be nice if you could modify the demo project so I can try it:

https://github.com/hpique/HPReorderTableView/tree/xslim

**Comment by erkanatesli** [comment]
It's still giving a crash when i drag a cell from section 1 to 0

Invalid update: invalid number of rows in section 0.  The number of rows contained in an existing section after the update (5) must be equal to the number of rows contained in that section before the update (5), plus or minus the number of rows inserted or deleted from that section (1 inserted, 0 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).

**Comment by xslim** [comment]
It's been long time ago I used it and tested it.
I don't work on that app anymore.

So you can cancel my PR probably.

**Pull request closed without merging**
